server:
  port: 9040 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: cn.hycat.service.statistics.service-cms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.233.128:8848 # nacos服务地址
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.233.128:3306/xsj_cms?serverTimezone=GMT%2B8
    username: root
    password: root
#spring:
  redis:
    host: 192.168.233.128
    port: 6379
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
#spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis日志
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

feign:
  sentinel:
    enabled: true