server:
  port: 9020 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.233.128:8848 # nacos服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    keyid: LTAI5t6kJbQ1wc1kYH5YwkDf
    keysecret: vnWDB7yXIrjqPZTI25rt11xJR5c9zu
    templateGroupId: VOD_NO_TRANSCODE
#    workflowId: 你配置的工作流id #工作流id