server:
  port: 9050 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
#spring:
  application:
    name: service-trade # 服务名
#spring:
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.233.128:3306/xsj_grade?serverTimezone=GMT%2B8
    username: root
    password: root
#spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd
    time-zone: GMT+8
#spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.233.128:8848 # nacos服务地址
#spring:
  redis:
    host: 192.168.233.128
    port: 6379
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#mybatis日志
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


feign:
  sentinel:
    enabled: true