server:
  port: 10000 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: infrastructure-apigateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.233.128:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务
      routes:
        - id: cn.hycat.service.statistics.service-edu
          uri: lb://cn.hycat.service.statistics.service-edu
          predicates:
            - Path=/user/**, /*/edu/**
        - id: cn.hycat.service.statistics.service-cms
          uri: lb://cn.hycat.service.statistics.service-cms
          predicates:
            - Path=/*/cms/**
        - id: cn.hycat.service.statistics.service-oss
          uri: lb://cn.hycat.service.statistics.service-oss
          predicates:
            - Path=/*/oss/**
        - id: cn.hycat.service.statistics.service-sms
          uri: lb://cn.hycat.service.statistics.service-sms
          predicates:
            - Path=/*/sms/**
        - id: cn.hycat.service.statistics.service-trade
          uri: lb://cn.hycat.service.statistics.service-trade
          predicates:
            - Path=/*/trade/**
        - id: cn.hycat.service.statistics.service-ucenter
          uri: lb://cn.hycat.service.statistics.service-ucenter
          predicates:
            - Path=/*/ucenter/**
        - id: cn.hycat.service.statistics.service-vod
          uri: lb://cn.hycat.service.statistics.service-vod
          predicates:
            - Path=/*/vod/**

