server:
  port: 9010 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
#spring:
  application:
    name: service-oss # 服务名
#spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.233.128:8848 # nacos服务地址

aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  bucketName: hycat-guliedu
  accessKeyId: LTAI5t6kJbQ1wc1kYH5YwkDf
  accessKeySecret: vnWDB7yXIrjqPZTI25rt11xJR5c9zu